### ISSUE TITLE
Pegasus Properties

### ISSUE THREAD

**Issue by 91nunocosta** [IKCAP/wings#34]
I noticed that Wings calls pegasus-plan with a generated configuration file (through --conf argument), this way overriding the local Pegasus configurations (located at $HOME/.pegasusrc). 

Is there any way to specify the intended Pegasus properties to be used by Wings?

**Comment by IKCAP** [comment]
@mayani This one is for you Rajiv

**Comment by mayani** [comment]
@91nunocosta Seems .pegasusrc is not picked up if --conf is provided. Not sure if that was by design or a bug.

Until we figure it out. Only way to deal with it is changing WINGS/Pegasus code. Is a simple change at one place in one file.

https://github.com/IKCAP/wings/blob/master/engines/pegasus/adapter/src/main/java/edu/isi/wings/execution/engine/api/impl/pegasus/PegasusWorkflowAdapter.java#L161

**Comment by mayani** [comment]
@91nunocosta I have changed the code so properties are passed as Java system properties. Pegasus should now pick up ~/.pegasusrc.
